<!DOCTYPE html>
<?php
require 'assets/php/connect.php';
?>
<html>
	<head>
        <title>GameGo.com</title>
        <base href="/" />
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>


	<body class="bg-success">

		<!-- Jumbotron Banner -->
		<div class="row jumbotron bg-light text-dark ml-3 mr-3 mt-3 rounded">
			<div class="col">
				<h1>
					<strong>
						Game<span class="text-success">Go</span>
					</strong>
				</h1>
				<p>Official Website of Dean Whelan and Maciek Shipshinsky</p>
			</div>
			
		</div>

		<!-- NavBar -->
		<nav class="navbar navbar-expand-lg navbar-light bg-light ml-3 mr-3 mt-3 rounded">
  			<a class="navbar-brand" href="#">
  				<img class="mr-3" src="assets/images/gamepad-icon.jpg" width="30" height="30" alt="Pad"> GameGo
  			</a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   				<span class="navbar-toggler-icon"></span>
  			</button>

  			<!-- Drop down menus -->
	  		<div class="collapse navbar-collapse" id="navbarSupportedContent">
	   			<ul class="navbar-nav mr-auto">

	    			<li class="nav-item active">
	        			<a class="nav-link text-success ml-3 mr-3" href="#">Home <span class="sr-only">(current)</span></a>
	      			</li>

	      			<li class="nav-item dropdown">
	        			<a class="nav-link text-success dropdown-toggle ml-3 mr-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          				Platform
	        			</a>
	        			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				        	<a class="dropdown-item" href="#">PC</a>
				        	<a class="dropdown-item" href="#">Playstation 4</a>
				        	<a class="dropdown-item" href="#">Xbox 1</a>
				        	<a class="dropdown-item" href="#">PS3/PS2</a>
				        	<a class="dropdown-item" href="#">Xbox360/Xbox</a>
				        	<a class="dropdown-item" href="#">Mobile</a>

				        	<div class="dropdown-divider"></div>
				        	<a class="dropdown-item" href="#">Browse by Platform</a>
				        </div>
	      			</li>

	      			<li class="nav-item dropdown">
	        			<a class="nav-link text-success dropdown-toggle ml-3 mr-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          				Genre
	        			</a>
	        			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				        	<a class="dropdown-item" href="#">Action/Adventure</a>
				        	<a class="dropdown-item" href="#">First Person Shooter</a>
				        	<a class="dropdown-item" href="#">Role Playing Games</a>
				        	<a class="dropdown-item" href="#">Strategy</a>
				        	<a class="dropdown-item" href="#">Simulation</a>
				        	<a class="dropdown-item" href="#">Puzzle Games</a>
				        	<a class="dropdown-item" href="#">VR Ready</a>

				        	<div class="dropdown-divider"></div>
				        	<a class="dropdown-item" href="#">Browse by Genre</a>
				        </div>
	      			</li>

	      			<li class="nav-item dropdown">
	        			<a class="nav-link text-success dropdown-toggle ml-3 mr-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          				Price Range
	        			</a>
	        			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				        	<a class="dropdown-item" href="#">€5 - €10</a>
				        	<a class="dropdown-item" href="#">€10 - €20</a>
				        	<a class="dropdown-item" href="#">€20 - €40</a>
				        	<a class="dropdown-item" href="#">€40 - €60</a>
				        	<a class="dropdown-item" href="#">€60+ </a>
				        	<div class="dropdown-divider"></div>
				        	<a class="dropdown-item" href="#">Browse by price</a>
				        </div>
	      			</li>
	    		</ul>
            </div>
		</nav>

        <main>
            <?php require_once($view); ?>
        </main>
	</body>


</html>