<div class="container">
   <br />
   <div class="form-group">
    <div class="input-group">
     <span class="input-group-addon">Search</span>
     <input type="text" name="search_text" id="search_text" placeholder="Search by Customer Details" class="form-control" />
    </div>
   </div>
   <br />
  </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 ">
                <h5> Filter Product </h5>
                <hr>
                <h6 class="text-info"> Select Brand</h6>
                <ul class="list-group">
                    <?php
                    $sql="SELECT DISTINCT brand from product order by brand";
                    $result=$conn->query($sql);
                    while($row=$result->fetch_assoc()) {
                ?>
                    <li class="list-group-item">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input product_check" value="<?= 
                                   $row['brand']; ?>" id="brand"><?= $row['brand']; ?>
                    </li>
                    <?php } ?>
                </ul>

                <h6 class="text-info"> Select Product</h6>
                <ul class="list-group">
                    <?php
                    $sql="SELECT DISTINCT product from product order by product";
                    $result=$conn->query($sql);
                    while($row=$result->fetch_assoc()) {
                ?>
                    <li class="list-group-item">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input product_check" value="<?= 
                                   $row['product']; ?>" id="product"><?= $row['product']; ?>
                    </li>
                    <?php } ?>
                </ul>

                <h6 class="text-info"> Select Size</h6>
                <ul class="list-group">
                    <?php
                    $sql="SELECT DISTINCT size from product order by size";
                    $result=$conn->query($sql);
                    while($row=$result->fetch_assoc()) {
                ?>
                    <li class="list-group-item">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input product_check" value="<?= 
                                   $row['size']; ?>" id="size"><?= $row['size']; ?>
                    </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="col-lg-9">
                <h5 class="text-center" id="textChange"> All Products </h5>
                <hr>
                <div class="text-center">
                    <img src="../assets/images/loader.gif" id="loader" width="200" style="display:none;">
                </div>
                <div class="row" id="result">
                    <?php
                        $sql="select * from product";
                        $result=$conn->query($sql);
                        while($row=$result->fetch_assoc()){
                    ?>
                    <div class="col-md-3 mb-2">
                        <div class="card-deck">
                            <div class="card border-secondary">
                                <img src="../assets/images/<?= $row['Image']; ?>" class="card-img-top" width="100" height="200">
                                <div class="card-img-overlay">
                                    <h6 style="margin-top:175px;" class="text-light bg-info text-center rounded p-1">
                                        <?= $row['Product']; ?>
                                    </h6>
                                </div>
                                <div class="card-body">
                                    <h4 class="card-title text-danger"> Price : 999 </h4>
                                    <p>
                                        Brand: <?= $row['Brand']; ?><br>
                                        Size: <?= $row['Size']; ?><br>
                                        Name: <?= $row['Product']; ?><br>
                                    </p>
                                    <a href="#" class="btn btn-success btn-block"> Add to Cart </a>

                                </div>
                            </div>
                        </div>
                    </div>
                        <?php } ?>
                </div>
            </div>
        </div>
    </div>
<script type="text/javascript">
    $(document).ready(function(){
        

        // when checkbox click do the following 
        $(".product_check").click(function(){
            //shows loader
            $("#loader").show();

            var action = 'data';
            var brand = get_filter_text('brand');
            var product = get_filter_text('product');
            var size = get_filter_text('size');

            //call ajax
            $.ajax({
                url:'action.php',
                method: 'POST',
                data:{action:action,brand:brand,product:product,size:size},
                success:function(response){
                    $("#result").html(response);
                    $("#loader").hide();
                    $("#textchange").text("Filtered Products");

                }
            });

        });
        //function to intialise the array 
        function get_filter_text(text_id){
            var filterData = [];
            //values in the input field get stored in the array 
            $('#'+text_id+':checked').each(function(){
                filterData.push($(this).val());
            });
            return filterData;
        }


        load_data();

        function load_data(query)
        {
        $.ajax({
        url:"fetch.php",
        method:"POST",
        data:{query:query},
        success:function(data)
        {
        $('#result').html(data);
        }
        });
        }
        $('#search_text').keyup(function(){
        var search = $(this).val();
        if(search != '')
        {
        load_data(search);
        }
        else
        {
        load_data();
        }
        });
    });


</script>